version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: tap-express-server
    container_name: tap-server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/tap
    networks:
      - app-network

  mongo:
    container_name: tap-mongodb
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: tap-react-client
    container_name: tap-client
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=http://localhost:4000
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
